// Code generated by "stringer -type=ID -output ./token_string.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_SELECT-57346]
	_ = x[T_FROM-57347]
	_ = x[T_WHERE-57348]
	_ = x[T_WITH-57349]
	_ = x[T_COUNT-57350]
	_ = x[T_LIMIT-57351]
	_ = x[T_OFFSET-57352]
	_ = x[T_ORDER_BY-57353]
	_ = x[T_DESC-57354]
	_ = x[T_ASC-57355]
	_ = x[T_LNUMBER-57356]
	_ = x[T_DNUMBER-57357]
	_ = x[T_CONSTANT_STRING-57358]
	_ = x[T_STRING-57359]
	_ = x[T_VARIABLE-57360]
	_ = x[T_COMMENT-57361]
	_ = x[T_DOC_COMMENT-57362]
	_ = x[T_WHITESPACE-57363]
	_ = x[T_OR-57364]
	_ = x[T_XOR-57365]
	_ = x[T_AND-57366]
	_ = x[T_NOT-57367]
	_ = x[T_EQUAL-57368]
	_ = x[T_NOT_EQUAL-57369]
	_ = x[T_SMALLER-57370]
	_ = x[T_GREATER-57371]
	_ = x[T_SMALLER_OR_EQUAL-57372]
	_ = x[T_GREATER_OR_EQUAL-57373]
	_ = x[T_OBJECT_OPERATOR-57374]
}

const _ID_name = "T_SELECTT_FROMT_WHERET_WITHT_COUNTT_LIMITT_OFFSETT_ORDER_BYT_DESCT_ASCT_LNUMBERT_DNUMBERT_CONSTANT_STRINGT_STRINGT_VARIABLET_COMMENTT_DOC_COMMENTT_WHITESPACET_ORT_XORT_ANDT_NOTT_EQUALT_NOT_EQUALT_SMALLERT_GREATERT_SMALLER_OR_EQUALT_GREATER_OR_EQUALT_OBJECT_OPERATOR"

var _ID_index = [...]uint16{0, 8, 14, 21, 27, 34, 41, 49, 59, 65, 70, 79, 88, 105, 113, 123, 132, 145, 157, 161, 166, 171, 176, 183, 194, 203, 212, 230, 248, 265}

func (i ID) String() string {
	i -= 57346
	if i < 0 || i >= ID(len(_ID_index)-1) {
		return "ID(" + strconv.FormatInt(int64(i+57346), 10) + ")"
	}
	return _ID_name[_ID_index[i]:_ID_index[i+1]]
}
